service:
  daemon: off
  flush: 1
  http_listen: 0.0.0.0
  http_port: 9880
  parsers_file: parsers.yaml 

pipeline:
  inputs: 
    - name: http
      tag:  vllm
      listen: 0.0.0.0
      port: 9880

  outputs:
    - name: file
      match: vllm
      file: vllm.log
      path: /var/log/
